import { createHash, randomUUID } from 'node:crypto';
import { HttpStatus, Injectable } from '@nestjs/common';
import { AppointmentStatus, BookingChannel, Prisma, SelectionMode, SlotHoldStatus } from '../../../../generated/appointment-client';
import type { PublicAuthContext } from '@platform';
import { AppointmentPrismaService } from '../database/prisma.service';
import { AppointmentDomainException } from '../common/domain.exception';
import { AppointmentDependencyGateway } from './dependency.gateway';
import { presentAppointment, presentHold } from './presenter';
import type { AppointmentListDto, CreateAppointmentDto, CreateHoldDto, ReassignDto, ReasonVersionDto, RescheduleDto, SlotQueryDto } from './dto';

type Ctx={requestId?:string;correlationId?:string;idempotencyKey?:string;actorAccountId?:string;actorRole?:string};
const STAFF=['RECEPTIONIST','ADMIN'];
@Injectable()
export class AppointmentDomainService {
 constructor(private readonly db:AppointmentPrismaService,private readonly deps:AppointmentDependencyGateway){}
 async listBookableSlots(q:SlotQueryDto,auth:PublicAuthContext){const from=new Date(q.from),to=new Date(q.to);this.interval(from,to);const offering=await this.deps.offering(q.serviceId,q.rankCode??'BASIC',from,this.ctx(auth));const specialty=offering.offering.requiredSpecialtyId;let doctors:any[]=[];if(q.selectionMode===SelectionMode.DOCTOR){if(!q.doctorId)this.fail(400,'VALIDATION_FAILED','doctorId required');const r=await this.deps.doctorEligibility(q.doctorId,specialty,this.ctx(auth));doctors=[r.doctor];}else{if(!q.rankCode)this.fail(400,'VALIDATION_FAILED','rankCode required');const r=await this.deps.eligibleDoctors(specialty,q.rankCode,from,to,this.ctx(auth));doctors=r.doctors??[];}const rows:any[]=[];for(const d of doctors){const av=await this.deps.doctorAvailability(d.doctorId,from,to,this.ctx(auth));for(const it of av.availableIntervals??[]){const s=this.ts(it.startAt),e=this.ts(it.endAt);if(!s||!e)continue;const occupied=await this.db.appointment.count({where:{assignedDoctorId:d.doctorId,status:{in:[AppointmentStatus.BOOKED,AppointmentStatus.REASSIGNMENT_REQUIRED,AppointmentStatus.CHECKED_IN,AppointmentStatus.IN_CLINICAL_CARE]},startAt:{lt:e},endAt:{gt:s}}});const held=await this.db.slotHold.count({where:{doctorId:d.doctorId,status:SlotHoldStatus.ACTIVE,expiresAt:{gt:new Date()},startAt:{lt:e},endAt:{gt:s}}});if(!occupied&&!held)rows.push({serviceId:q.serviceId,selectionMode:q.selectionMode,doctorId:q.selectionMode===SelectionMode.DOCTOR?d.doctorId:null,rankCode:d.consultationRankCode,startAt:s,endAt:e,availableCapacity:1});if(rows.length>=(q.limit??20))break;}if(rows.length>=(q.limit??20))break;}return{items:rows,nextPageToken:null};}
 async createHold(dto:CreateHoldDto,auth:PublicAuthContext,key?:string){const idem=this.key(key),patientId=this.patientId(dto.patientId,auth);this.selection(dto.selectionMode,dto.requestedDoctorId,dto.requestedRankCode);const start=new Date(dto.startAt),end=new Date(dto.endAt);this.interval(start,end);const ctx=this.ctx(auth,idem);const eligibility=await this.deps.patientEligibility(patientId,ctx);if(!eligibility.eligibleForBooking)this.fail(422,'PATIENT_NOT_ELIGIBLE','Patient not eligible');if(auth.role==='PATIENT'&&!eligibility.callerOwnsPatient)this.fail(403,'FORBIDDEN','Patient ownership mismatch');let doctor:any,rank=dto.requestedRankCode??'';const firstOffering=await this.deps.offering(dto.serviceId,rank||'BASIC',start,ctx);const specialty=firstOffering.offering.requiredSpecialtyId;if(dto.selectionMode===SelectionMode.DOCTOR){const result=await this.deps.doctorEligibility(dto.requestedDoctorId!,specialty,ctx);doctor=result.doctor;rank=doctor.consultationRankCode;}else{const result=await this.deps.eligibleDoctors(specialty,rank,start,end,ctx);doctor=result.doctors?.[0];}if(!doctor||doctor.status!=='DOCTOR_OPERATIONAL_STATUS_ACTIVE')this.fail(422,'DOCTOR_NOT_ELIGIBLE','No eligible doctor');const av=await this.deps.doctorAvailability(doctor.doctorId,start,end,ctx);if(!(av.availableIntervals??[]).some((x:any)=>{const s=this.ts(x.startAt),e=this.ts(x.endAt);return s&&e&&s<=start&&e>=end;}))this.fail(409,'SLOT_NOT_AVAILABLE','Doctor not available');const hash=this.hash(dto);const replay=await this.replay('create-hold',idem,hash);if(replay)return replay;try{return await this.db.$transaction(async tx=>{await tx.slotHold.updateMany({where:{status:SlotHoldStatus.ACTIVE,expiresAt:{lte:new Date()}},data:{status:SlotHoldStatus.EXPIRED}});const overlap=await Promise.all([tx.appointment.count({where:{assignedDoctorId:doctor.doctorId,status:{in:[AppointmentStatus.BOOKED,AppointmentStatus.REASSIGNMENT_REQUIRED,AppointmentStatus.CHECKED_IN,AppointmentStatus.IN_CLINICAL_CARE]},startAt:{lt:end},endAt:{gt:start}}}),tx.slotHold.count({where:{doctorId:doctor.doctorId,status:SlotHoldStatus.ACTIVE,expiresAt:{gt:new Date()},startAt:{lt:end},endAt:{gt:start}}})]);if(overlap[0]||overlap[1])this.fail(409,'SLOT_NOT_AVAILABLE','Slot no longer available');const hold=await tx.slotHold.create({data:{patientId,serviceId:dto.serviceId,doctorId:doctor.doctorId,rankCode:rank,selectionMode:dto.selectionMode,startAt:start,endAt:end,expiresAt:new Date(Date.now()+300000)}});const body=presentHold(hold);await tx.appointmentIdempotencyRecord.create({data:{scope:'create-hold',key:idem,requestHash:hash,resourceId:hold.id,responseStatus:201,responseBody:body as any}});return body;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(e){if(e instanceof AppointmentDomainException)throw e;this.fail(409,'SLOT_NOT_AVAILABLE','Concurrent slot conflict');}}
 async releaseHold(id:string,auth:PublicAuthContext){const hold=await this.db.slotHold.findUnique({where:{id}});if(!hold)this.fail(404,'HOLD_NOT_FOUND','Hold not found');await this.authorizePatient(hold.patientId,auth);if(hold.status===SlotHoldStatus.ACTIVE)await this.db.slotHold.update({where:{id},data:{status:SlotHoldStatus.RELEASED}});}
 async createAppointment(dto:CreateAppointmentDto,auth:PublicAuthContext,key?:string){const idem=this.key(key),hash=this.hash(dto),ctx=this.ctx(auth,idem);const replay=await this.replay('create-appointment',idem,hash);if(replay)return replay;const hold=await this.db.slotHold.findUnique({where:{id:dto.holdId}});if(!hold)this.fail(404,'HOLD_NOT_FOUND','Hold not found');await this.authorizePatient(hold.patientId,auth);if(hold.status!==SlotHoldStatus.ACTIVE||hold.expiresAt<=new Date())this.fail(409,'HOLD_EXPIRED','Hold expired');const eligibility=await this.deps.patientEligibility(hold.patientId,ctx);if(!eligibility.eligibleForBooking)this.fail(422,'PATIENT_NOT_ELIGIBLE','Patient not eligible');const offering=(await this.deps.offering(hold.serviceId,hold.rankCode,hold.startAt,ctx)).offering;const doctor=(await this.deps.doctorEligibility(hold.doctorId,offering.requiredSpecialtyId,ctx)).doctor;if(doctor.status!=='DOCTOR_OPERATIONAL_STATUS_ACTIVE'||doctor.consultationRankCode!==hold.rankCode)this.fail(422,'DOCTOR_NOT_ELIGIBLE','Doctor changed');const estimate=await this.deps.queueEstimate(offering.serviceCode||'INITIAL',hold.doctorId,hold.startAt,ctx);return this.db.$transaction(async tx=>{const consumed=await tx.slotHold.updateMany({where:{id:hold.id,status:SlotHoldStatus.ACTIVE,expiresAt:{gt:new Date()}},data:{status:SlotHoldStatus.CONSUMED}});if(consumed.count!==1)this.fail(409,'HOLD_EXPIRED','Hold expired');const appointment=await tx.appointment.create({data:{appointmentCode:this.code(),patientId:hold.patientId,serviceId:hold.serviceId,channel:dto.channel,selectionMode:hold.selectionMode,requestedDoctorId:hold.selectionMode===SelectionMode.DOCTOR?hold.doctorId:null,requestedRankCode:hold.selectionMode===SelectionMode.RANK?hold.rankCode:null,assignedDoctorId:hold.doctorId,assignedRankCode:hold.rankCode,specialtyId:offering.requiredSpecialtyId,startAt:hold.startAt,endAt:hold.endAt,serviceNameSnapshot:offering.serviceName,serviceVersion:Number(offering.serviceVersion),basePriceId:offering.basePriceId,baseAmountMinor:BigInt(offering.basePrice.amountMinor),rankSurchargePriceId:offering.rankSurchargeId||null,rankSurchargeAmountMinor:BigInt(offering.rankSurcharge.amountMinor),estimatedTotalMinor:BigInt(offering.totalPrice.amountMinor),availabilityVersion:BigInt(doctor.availabilityVersion),queueEstimateMinutes:estimate?.estimatedWaitMinutes??null}});await tx.slotHold.update({where:{id:hold.id},data:{consumedByAppointmentId:appointment.id}});await this.auditOutbox(tx,appointment,'appointment.booked.v1',auth.userId);const body=presentAppointment(appointment);await tx.appointmentIdempotencyRecord.create({data:{scope:'create-appointment',key:idem,requestHash:hash,resourceId:appointment.id,responseStatus:201,responseBody:body as any}});return body;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
 async get(id:string,auth?:PublicAuthContext){const x=await this.db.appointment.findUnique({where:{id}});if(!x)this.fail(404,'APPOINTMENT_NOT_FOUND','Appointment not found');if(auth)await this.authorizePatient(x.patientId,auth);return presentAppointment(x);}
 async list(q:AppointmentListDto,auth:PublicAuthContext){let patientId=q.patientId;if(auth.role==='PATIENT'){if(!patientId)this.fail(400,'PATIENT_ID_REQUIRED','patientId required');await this.authorizePatient(patientId,auth);}else if(!STAFF.includes(auth.role))this.fail(403,'FORBIDDEN','Staff only');const rows=await this.db.appointment.findMany({where:{...(patientId?{patientId}:{}),...(q.status?{status:q.status as AppointmentStatus}:{}),...(q.from||q.to?{startAt:{...(q.from?{gte:new Date(q.from)}:{}),...(q.to?{lte:new Date(q.to)}:{})}}:{})},orderBy:[{startAt:'desc'},{id:'asc'}],take:(q.limit??20)+1,...(q.cursor?{cursor:{id:q.cursor},skip:1}:{})});const items=rows.slice(0,q.limit??20);return{items:items.map(presentAppointment),nextPageToken:rows.length>(q.limit??20)?items.at(-1)?.id:null};}
 async cancel(id:string,dto:ReasonVersionDto,auth:PublicAuthContext,key?:string){this.staff(auth);return this.transition(id,dto.expectedVersion,[AppointmentStatus.BOOKED,AppointmentStatus.REASSIGNMENT_REQUIRED],AppointmentStatus.CANCELLED,{cancellationReason:dto.reason},'appointment.cancelled.v1',auth,key,dto);}
 async reschedule(id:string,dto:RescheduleDto,auth:PublicAuthContext,key?:string){this.staff(auth);const current=await this.db.appointment.findUnique({where:{id}}),hold=await this.db.slotHold.findUnique({where:{id:dto.newHoldId}});if(!current||!hold)this.fail(404,'RESOURCE_NOT_FOUND','Appointment or hold missing');if(hold.patientId!==current.patientId||hold.status!==SlotHoldStatus.ACTIVE||hold.expiresAt<=new Date())this.fail(409,'INVALID_HOLD_STATE','Invalid new hold');const offering=(await this.deps.offering(hold.serviceId,hold.rankCode,hold.startAt,this.ctx(auth,key))).offering;return this.db.$transaction(async tx=>{const u=await tx.appointment.updateMany({where:{id,version:dto.expectedVersion,status:{in:[AppointmentStatus.BOOKED,AppointmentStatus.REASSIGNMENT_REQUIRED]}},data:{serviceId:hold.serviceId,selectionMode:hold.selectionMode,assignedDoctorId:hold.doctorId,assignedRankCode:hold.rankCode,specialtyId:offering.requiredSpecialtyId,startAt:hold.startAt,endAt:hold.endAt,serviceNameSnapshot:offering.serviceName,serviceVersion:Number(offering.serviceVersion),basePriceId:offering.basePriceId,baseAmountMinor:BigInt(offering.basePrice.amountMinor),rankSurchargePriceId:offering.rankSurchargeId||null,rankSurchargeAmountMinor:BigInt(offering.rankSurcharge.amountMinor),estimatedTotalMinor:BigInt(offering.totalPrice.amountMinor),status:AppointmentStatus.BOOKED,rescheduleCount:{increment:1},version:{increment:1}}});if(u.count!==1)this.fail(409,'VERSION_CONFLICT','Stale appointment');await tx.slotHold.update({where:{id:hold.id},data:{status:SlotHoldStatus.CONSUMED,consumedByAppointmentId:id}});const x=await tx.appointment.findUnique({where:{id}});await this.auditOutbox(tx,x!,'appointment.rescheduled.v1',auth.userId,dto.reason);return presentAppointment(x);});}
 async reassign(id:string,dto:ReassignDto,auth:PublicAuthContext,key?:string){this.staff(auth);const current=await this.db.appointment.findUnique({where:{id}});if(!current)this.fail(404,'APPOINTMENT_NOT_FOUND','Not found');const doctor=(await this.deps.doctorEligibility(dto.doctorId,current.specialtyId,this.ctx(auth,key))).doctor;if(doctor.status!=='DOCTOR_OPERATIONAL_STATUS_ACTIVE')this.fail(422,'DOCTOR_NOT_ELIGIBLE','Doctor not eligible');return this.db.$transaction(async tx=>{const u=await tx.appointment.updateMany({where:{id,version:dto.expectedVersion,status:{in:[AppointmentStatus.BOOKED,AppointmentStatus.REASSIGNMENT_REQUIRED]}},data:{assignedDoctorId:dto.doctorId,assignedRankCode:doctor.consultationRankCode,status:AppointmentStatus.BOOKED,version:{increment:1}}});if(u.count!==1)this.fail(409,'VERSION_CONFLICT','Stale appointment');await tx.appointmentAssignmentHistory.create({data:{appointmentId:id,fromDoctorId:current.assignedDoctorId,toDoctorId:dto.doctorId,rankCode:doctor.consultationRankCode,reason:dto.reason+' | '+dto.confirmationEvidence,actorId:auth.userId}});const x=await tx.appointment.findUnique({where:{id}});await this.auditOutbox(tx,x!,'appointment.reassigned.v1',auth.userId,dto.reason);return presentAppointment(x);});}
 async validateAdmission(id:string,patientId:string){const x=await this.db.appointment.findUnique({where:{id}});if(!x||x.patientId!==patientId)return{valid:false,failureCode:'APPOINTMENT_NOT_FOUND'};return{valid:x.status===AppointmentStatus.BOOKED,failureCode:x.status===AppointmentStatus.BOOKED?'':'INVALID_STATE',appointment:presentAppointment(x),lateMinutes:Math.max(0,Math.floor((Date.now()-x.startAt.getTime())/60000))};}
 async checkIn(id:string,input:any,key?:string){if(!['PAID','APPROVED_CREDIT','ADMISSION_PAYMENT_CONDITION_PAID','ADMISSION_PAYMENT_CONDITION_APPROVED_CREDIT'].includes(input.paymentCondition))this.fail(422,'PAYMENT_CONDITION_NOT_MET','Payment required');return this.transition(id,Number(input.expectedVersion),[AppointmentStatus.BOOKED],AppointmentStatus.CHECKED_IN,{receptionCaseId:input.receptionCaseId,encounterId:input.encounterId,checkedInAt:input.checkedInAt??new Date()},'appointment.checked_in.v1',{userId:input.actorId??'',role:'RECEPTIONIST'},key,input);}
 markClinicalStarted(id:string,input:any,key?:string){return this.transition(id,Number(input.expectedVersion),[AppointmentStatus.CHECKED_IN],AppointmentStatus.IN_CLINICAL_CARE,{encounterId:input.encounterId,clinicalStartedAt:input.startedAt??new Date()},'appointment.clinical_started.v1',{userId:'medical-record-service',role:'SERVICE'},key,input);}
 markClinicalCompleted(id:string,input:any,key?:string){return this.transition(id,Number(input.expectedVersion),[AppointmentStatus.CHECKED_IN,AppointmentStatus.IN_CLINICAL_CARE],AppointmentStatus.COMPLETED,{encounterId:input.encounterId,completedAt:input.completedAt??new Date()},'appointment.completed.v1',{userId:'medical-record-service',role:'SERVICE'},key,input);}
 markNoShow(id:string,input:any,key?:string){return this.transition(id,Number(input.expectedVersion),[AppointmentStatus.BOOKED],AppointmentStatus.NO_SHOW,{},'appointment.no_show.v1',{userId:'system',role:'SERVICE'},key,input);}
 private async transition(id:string,version:number,from:AppointmentStatus[],to:AppointmentStatus,data:any,event:string,auth:{userId:string;role:string},key?:string,payload?:any){const idem=key?this.key(key):undefined;const hash=this.hash(payload??{});if(idem){const r=await this.replay(event,idem,hash);if(r)return r;}return this.db.$transaction(async tx=>{const u=await tx.appointment.updateMany({where:{id,version,status:{in:from}},data:{...data,status:to,version:{increment:1}}});if(u.count!==1)this.fail(409,'INVALID_STATE_TRANSITION','Invalid state or version');const x=await tx.appointment.findUnique({where:{id}});await this.auditOutbox(tx,x!,event,auth.userId,data.cancellationReason);const body=presentAppointment(x);if(idem)await tx.appointmentIdempotencyRecord.create({data:{scope:event,key:idem,requestHash:hash,resourceId:id,responseStatus:200,responseBody:body as any}});return body;});}
 private async authorizePatient(patientId:string,auth:PublicAuthContext){if(STAFF.includes(auth.role))return;if(auth.role!=='PATIENT')this.fail(403,'FORBIDDEN','Forbidden');const x=await this.deps.patientEligibility(patientId,this.ctx(auth));if(!x.callerOwnsPatient)this.fail(404,'APPOINTMENT_NOT_FOUND','Not found');}
 private patientId(value:string|undefined,auth:PublicAuthContext){if(!value)this.fail(400,'PATIENT_ID_REQUIRED','patientId required');if(auth.role!=='PATIENT'&&!STAFF.includes(auth.role))this.fail(403,'FORBIDDEN','Forbidden');return value;}
 private staff(auth:PublicAuthContext){if(!STAFF.includes(auth.role))this.fail(403,'FORBIDDEN','Staff only');}
 private selection(mode:SelectionMode,doctor?:string,rank?:string){if((mode===SelectionMode.DOCTOR)!==Boolean(doctor)||(mode===SelectionMode.RANK)!==Boolean(rank))this.fail(400,'VALIDATION_FAILED','Exactly one doctor or rank is required');}
 private interval(s:Date,e:Date){if(!(s<e)||Number.isNaN(s.getTime())||Number.isNaN(e.getTime()))this.fail(400,'VALIDATION_FAILED','Invalid interval');}
 private key(v?:string){if(!v||v.length>128)this.fail(400,'IDEMPOTENCY_KEY_REQUIRED','Idempotency-Key required');return v;}
 private hash(v:any){return createHash('sha256').update(JSON.stringify(v)).digest('hex');}
 private async replay(scope:string,key:string,hash:string){const x=await this.db.appointmentIdempotencyRecord.findUnique({where:{scope_key:{scope,key}}});if(!x)return null;if(x.requestHash!==hash)this.fail(409,'IDEMPOTENCY_KEY_REUSED','Key reused');return x.responseBody;}
 private code(){return 'APT'+Date.now().toString(36).toUpperCase()+randomUUID().replace(/-/g,'').slice(0,6).toUpperCase();}
 private ts(x:any){if(!x)return undefined;return new Date(Number(x.seconds)*1000+Math.floor(Number(x.nanos??0)/1e6));}
 private ctx(auth:PublicAuthContext,key?:string):Ctx{return{requestId:randomUUID(),correlationId:randomUUID(),idempotencyKey:key,actorAccountId:auth.userId,actorRole:auth.role};}
 private async auditOutbox(tx:any,x:any,event:string,actorId?:string,reason?:string){await tx.appointmentAuditLog.create({data:{eventType:event,actorId:actorId||null,resourceId:x.id,reason:reason||null}});await tx.appointmentOutboxEvent.create({data:{eventType:event,aggregateId:x.id,aggregateVersion:x.version,payload:{eventVersion:1,aggregateType:'appointment',aggregateId:x.id,data:{appointmentId:x.id,patientId:x.patientId,status:x.status}}}});}
 private fail(status:number,code:string,message:string):never{throw new AppointmentDomainException(code,message,status);}
}
