import { Injectable, ServiceUnavailableException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GrpcClientFactory, dateToTimestamp } from '@platform';

@Injectable()
export class AppointmentDependencyGateway {
  constructor(private readonly config:ConfigService,private readonly grpc:GrpcClientFactory){}
  private target(key:string, fallback:string){return this.config.get<string>(key)??fallback;}
  private ctx(c:{requestId?:string;correlationId?:string;idempotencyKey?:string;actorAccountId?:string;actorRole?:string}){return {requestId:c.requestId??'',correlationId:c.correlationId??c.requestId??'',idempotencyKey:c.idempotencyKey??'',actorAccountId:c.actorAccountId??'',actorRole:c.actorRole??''};}
  async patientEligibility(patientId:string,c:any){return this.call('patient','PATIENT_GRPC_TARGET','patient-service:6004','patient/v1/patient_internal.proto','maternal.patient.v1','PatientInternalService','getPatientEligibility',{context:this.ctx(c),patientId},['patient:eligibility:read'],'patient-service');}
  async doctorEligibility(doctorId:string,specialtyId:string,c:any){return this.call('doctor','DOCTOR_GRPC_TARGET','doctor-service:6005','doctor/v1/doctor_internal.proto','maternal.doctor.v1','DoctorInternalService','getDoctorEligibility',{context:this.ctx(c),doctorId,requiredSpecialtyId:specialtyId},['doctor:internal:read'],'doctor-service');}
  async eligibleDoctors(specialtyId:string,rankCode:string,start:Date,end:Date,c:any){return this.call('doctor','DOCTOR_GRPC_TARGET','doctor-service:6005','doctor/v1/doctor_internal.proto','maternal.doctor.v1','DoctorInternalService','listEligibleDoctors',{context:this.ctx(c),specialtyId,consultationRankCode:rankCode,intervalStart:dateToTimestamp(start),intervalEnd:dateToTimestamp(end),page:{pageSize:20,pageToken:''}},['doctor:internal:read'],'doctor-service');}
  async doctorAvailability(doctorId:string,start:Date,end:Date,c:any){return this.call('doctor','DOCTOR_GRPC_TARGET','doctor-service:6005','doctor/v1/doctor_internal.proto','maternal.doctor.v1','DoctorInternalService','getDoctorAvailability',{context:this.ctx(c),doctorId,rangeStart:dateToTimestamp(start),rangeEnd:dateToTimestamp(end)},['doctor:internal:read'],'doctor-service');}
  async offering(serviceId:string,rankCode:string,at:Date,c:any){return this.call('catalog','CATALOG_GRPC_TARGET','service-catalog-service:6007','catalog/v1/catalog_internal.proto','maternal.catalog.v1','CatalogInternalService','resolveBookingOffering',{context:this.ctx(c),serviceId,consultationRankCode:rankCode,effectiveAt:dateToTimestamp(at)},['catalog:resolve'],'service-catalog-service');}
  async queueEstimate(stageCode:string,doctorId:string,at:Date,c:any){try{return await this.call('queue','QUEUE_GRPC_TARGET','queue-service:6012','queue/v1/queue_internal.proto','maternal.queue.v1','QueueInternalService','estimateWait',{context:this.ctx(c),stageCode,doctorId,expectedArrivalAt:dateToTimestamp(at)},['queue:estimate'],'queue-service',800);}catch{return null;}}
  async paymentCondition(invoiceId:string,appointmentId:string,c:any){return this.call('billing','BILLING_GRPC_TARGET','billing-service:6009','billing/v1/billing_internal.proto','maternal.billing.v1','BillingInternalService','getAdmissionPaymentCondition',{context:this.ctx(c),invoiceId,appointmentId},['billing:read'],'billing-service');}
  private async call(key:string,env:string,fallback:string,proto:string,pkg:string,service:string,method:string,request:any,scopes:string[],audience:string,deadline=2000):Promise<any>{try{const client=this.grpc.client({key,target:this.target(env,fallback),proto,package:pkg,service});const metadata=this.grpc.metadata(audience,scopes,{requestId:request.context?.requestId,correlationId:request.context?.correlationId,idempotencyKey:request.context?.idempotencyKey});return await this.grpc.unary(client,method,request,metadata,deadline);}catch(error){throw new ServiceUnavailableException('DEPENDENCY_UNAVAILABLE: '+key);}}
}
