ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'VERIFY_PATIENT_IDENTITY';
ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'OPEN_RECEPTION_CASE';
ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'CREATE_OR_GET_BASE_INVOICE';
ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'VERIFY_PAYMENT_OR_APPROVED_CREDIT';
ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'OPEN_CLINICAL_ENCOUNTER_DRAFT';
ALTER TYPE "AdmissionStep" ADD VALUE IF NOT EXISTS 'CREATE_AUTHORITATIVE_QUEUE_TICKET';
ALTER TABLE "admissions" ADD COLUMN IF NOT EXISTS "encounter_id" UUID;
ALTER TABLE "admissions" ADD COLUMN IF NOT EXISTS "queue_journey_id" UUID;
