import { Injectable } from '@nestjs/common';import { ConfigService } from '@nestjs/config';import { GrpcClientFactory,dateToTimestamp } from '@platform';
@Injectable()export class AdmissionGrpcGateway{constructor(private readonly cfg:ConfigService,private readonly grpc:GrpcClientFactory){}private ctx(actor:string,key:string){return{requestId:key,correlationId:key,idempotencyKey:key,actorAccountId:actor,actorRole:'RECEPTIONIST'};}private async call(key:string,target:string,proto:string,pkg:string,svc:string,method:string,request:any,aud:string,scopes:string[],write=true):Promise<any>{const client=this.grpc.client({key,target:this.cfg.get<string>(target)??this.fallback(target),proto,package:pkg,service:svc});return this.grpc.unary(client,method,request,this.grpc.metadata(aud,scopes,{requestId:request.context.requestId,correlationId:request.context.correlationId,idempotencyKey:write?request.context.idempotencyKey:undefined}),write?3000:2000);}private fallback(k:string){return({APPOINTMENT_GRPC_TARGET:'appointment-service:6008',PATIENT_GRPC_TARGET:'patient-service:6004',BILLING_GRPC_TARGET:'billing-service:6009',MEDICAL_RECORD_GRPC_TARGET:'medical-record-service:6011',QUEUE_GRPC_TARGET:'queue-service:6012'} as any)[k];}
validateAppointment(id:string,patientId:string,caseId:string,actor:string,key:string){return this.call('appointment','APPOINTMENT_GRPC_TARGET','appointment/v1/appointment_internal.proto','maternal.appointment.v1','AppointmentInternalService','validateForAdmission',{context:this.ctx(actor,key),appointmentId:id,patientId,receptionCaseId:caseId},'appointment-service',['appointment:admission:read'],false);}
getAppointment(id:string,actor:string,key:string){return this.call('appointment','APPOINTMENT_GRPC_TARGET','appointment/v1/appointment_internal.proto','maternal.appointment.v1','AppointmentInternalService','getAppointment',{context:this.ctx(actor,key),appointmentId:id},'appointment-service',['appointment:internal:read'],false);}
patientIdentity(id:string,actor:string,key:string){return this.call('patient','PATIENT_GRPC_TARGET','patient/v1/patient_internal.proto','maternal.patient.v1','PatientInternalService','getPatientIdentity',{context:this.ctx(actor,key),patientId:id,purpose:'ADMISSION'},'patient-service',['patient:identity:read'],false);}
createInvoice(a:any,caseId:string,actor:string,key:string){const p=a.pricing;return this.call('billing','BILLING_GRPC_TARGET','billing/v1/billing_internal.proto','maternal.billing.v1','BillingInternalService','createOrGetBaseInvoice',{context:this.ctx(actor,key),appointmentId:a.appointmentId,patientId:a.patientId,appointmentVersion:a.version,receptionCaseId:caseId,pricing:{serviceId:a.serviceId,serviceName:p.serviceName,serviceVersion:p.serviceVersion,assignedRankCode:a.assignedRankCode,basePriceId:p.basePriceId,baseAmount:p.baseAmount,rankSurchargePriceId:p.rankSurchargePriceId,rankSurchargeAmount:p.rankSurchargeAmount,estimatedTotal:p.estimatedTotal}},'billing-service',['billing:invoice:write']);}
paymentCondition(invoiceId:string,appointmentId:string,actor:string,key:string){return this.call('billing-read','BILLING_GRPC_TARGET','billing/v1/billing_internal.proto','maternal.billing.v1','BillingInternalService','getAdmissionPaymentCondition',{context:this.ctx(actor,key),invoiceId,appointmentId},'billing-service',['billing:read'],false);}
openEncounter(v:any,invoiceId:string,caseId:string,actor:string,key:string){return this.call('medical','MEDICAL_RECORD_GRPC_TARGET','medical_record/v1/medical_record_internal.proto','maternal.medical_record.v1','MedicalRecordInternalService','openOrGetEncounter',{context:this.ctx(actor,key),appointmentId:v.appointmentId,patientId:v.patientId,primaryDoctorId:v.assignedDoctorId,admission:{receptionCaseId:caseId,invoiceId,paymentCondition:'PAID',checkedInAt:dateToTimestamp(new Date())}},'medical-record-service',['medical:encounter:open']);}
checkIn(a:any,caseId:string,invoiceId:string,encounterId:string,condition:string,actor:string,key:string){return this.call('appointment-write','APPOINTMENT_GRPC_TARGET','appointment/v1/appointment_internal.proto','maternal.appointment.v1','AppointmentInternalService','checkInAppointment',{context:this.ctx(actor,key),appointmentId:a.appointmentId,receptionCaseId:caseId,invoiceId,paymentCondition:'ADMISSION_PAYMENT_CONDITION_'+condition,encounterId,checkedInAt:dateToTimestamp(new Date()),expectedVersion:a.version},'appointment-service',['appointment:checkin']);}
createQueue(a:any,caseId:string,invoiceId:string,encounterId:string,condition:string,actor:string,key:string){return this.call('queue','QUEUE_GRPC_TARGET','queue/v1/queue_internal.proto','maternal.queue.v1','QueueInternalService','createOrGetJourney',{context:this.ctx(actor,key),appointmentId:a.appointmentId,patientId:a.patientId,encounterId,initialStageCode:'CONSULTATION',roomCode:'',scheduledAt:a.startAt,arrivalAt:dateToTimestamp(new Date()),admission:{receptionCaseId:caseId,invoiceId,paymentCondition:condition,checkedInAt:dateToTimestamp(new Date())}},'queue-service',['queue:journey:create']);}}
